site_name: Swarmchestrate Docs
repo_url: https://github.com/Swarmchestrate/tosca
site_url: https://docs.swarmchestrate.eu
theme: 
  name: material
  logo: img/word-logo.png
  favicon: favicon.png
  palette:
    primary: blue
    accent: light blue
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

nav:
  - Home: index.md
  - Authors:
    - Applications: sat.md
    - Capacities: cdt.md
  - Microservice Spec: microservice.md
  - Policy Spec: policy.md
  - Capacity Spec: capacity.md
  - Monitoring: monitoring.md
  - Sardou:
    - Overview: sardou.md
    - Working with Sardou: sardou_lib.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
