tosca_definitions_version: tosca_2_0

description: UoW AWS Capacity Def

metadata:
  name: cap-aws-uow
  author: University of Westminster
  date: 2026-03-04
  version: 0.2
  tags:
  - provider: uow

imports:
- namespace: swch
  url: https://raw.githubusercontent.com/Swarmchestrate/tosca/refs/heads/main/profiles/eu.swarmchestrate/profile.yaml

node_types:

  EC2Base:
    derived_from: swch:Capacity
    description: >
      An base compute node from the UoW AWS provision
    properties:
      ami:
        type: string
        required: true
        description: >
          The Amazon Machine ID of the image used to launch the instance.
        default: ami-0ba0c1a358147d1a8
      instance_type:
        type: string
        required: true
        description: >
          The AWS instance type (e.g., t2.micro) specifying compute resources.
      key_name:
        type: string
        required: false
        description: >
          The name of the SSH key pair used to access the instance.
        default: g
      security_groups:
        type: list
        required: false
        entry_schema: string
        description: >
          A list of security group IDs that control inbound and outbound traffic for the instance.

    capabilities:
      host:
        properties:
          disk-size:
            default: 8
          bandwidth:
            default: 1000
      os:
        properties:
          type:
            default: linux
          version:
            default: 2023
          distribution:
            default: amazon
      resource:
        properties:
          provider:
            default: UoW
          capacity-provider:
            default: UoW
          type:
            default: cloud
      network:
        properties:
          ipv4_enabled:
            default: True
          ipv6_enabled:
            default: False
          type:
            default: ethernet
      locality:
        properties:
          continent:
            default: Europe
          country:
            default: United Kingdom
          city:
            default: London
      energy:
        properties:
          powered-type:
            default: mains-powered
          energy-type:
            default: non-green

    t3-micro:
      derived_from: EC2Base
      properties:
        instance_type:
          default: t3.micro
      capabilities:
        capacity:
          properties:
            instances:
              default: 10
        host:
          properties:
            num-cpus: 
              default: 2
            mem-size:
              default: 1
        pricing:
          properties:
            cost:
              default: 0.0118
        energy:
          properties:
            consumption: 
              default: 0.10


    t3-small:
      derived_from: EC2Base
      properties:
        instance_type:
          default: t3.small
      capabilities:
        capacity:
          properties:
            instances:
              default: 10
        host:
          properties:
            num-cpus: 
              default: 2
            mem-size:
              default: 2
        pricing:
          properties:
            cost:
              default: 0.042
        energy:
          properties:
            consumption: 
              default: 0.10


    t3-medium:
      derived_from: EC2Base
      properties:
        instance_type:
          default: t3.medium
      capabilities:
        capacity:
          properties:
            instances:
              default: 5
        host:
          properties:
            num-cpus: 
              default: 2
            mem-size:
              default: 4
        pricing:
          properties:
            cost:
              default: 0.0472
        energy:
          properties:
            consumption: 
              default: 0.10