name: Parse for validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Puccini
        run: make install

      - name: Run YAML Parsing
        run: make parse
